dist: bionic
branches:
  only:
  - master
jobs:
  allow_failures:
    - if: branch = master
  include:
    - # Disable build for every commit
      if: TRAVIS_EVENT_TYPE = cron
before_script:
  - GAMA_LINUX=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_withJDK_Linux | cut -d ':' -f 2,3 | tr -d \")
  - GAMA_MAC=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_withJDK_Mac | cut -d ':' -f 2,3 | tr -d \")
  - GAMA_WINDOWS=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_withJDK_Win | cut -d ':' -f 2,3 | tr -d \")
script:
  # Linux build
  - curl -o gama.zip -fSL $GAMA_LINUX
  - unzip gama.zip -d ./GAMA
  - chmod +x ./GAMA/headless/gama-headless.sh
  # Create Library folders
  - mkdir -p ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
  - cp -r COMOKIT ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
  - zip -r --symlinks ./COMOKIT-Linux.zip ./GAMA

  # Clean GAMA version
  - rm -fr ./GAMA

  # Mac build
  - curl -o gama.zip -fSL $GAMA_MAC
  - unzip gama.zip -d ./GAMA
  - chmod +x ./GAMA/Gama.app/Contents/headless/gama-headless.sh
  # Create Library folders
  - mkdir -p ./GAMA/Gama.app/Contents/Eclipse/configuration/org.eclipse.osgi/15/0/.cp/models/
  - cp -r COMOKIT ./GAMA/Gama.app/Contents/Eclipse/configuration/org.eclipse.osgi/15/0/.cp/models/
  - zip -r --symlinks ./COMOKIT-Mac.zip ./GAMA/Gama.app

  # Clean GAMA version
  - rm -fr ./GAMA

  # Windows build
  - curl -o gama.zip -fSL $GAMA_WINDOWS
  - unzip gama.zip -d ./GAMA
  # Create Library folders
  - mkdir -p ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
  - cp -r COMOKIT ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
  - zip -r --symlinks ./COMOKIT-Win.zip ./GAMA

before_deploy:
  - git remote add master https://${GITHUB_API_KEY}@github.com/COMOKIT/COMOKIT-Model.git
  - git fetch master --tags
  - git tag -f latest
  - git push master --tags -f
deploy:
  provider: releases
  name: "All-In-One Archive"
  body: "Prerelease of COMOKIT archived with GAMA JDK Continuous and COMOKIT's default models (in Library model)"
  overwrite: true
  tag_name: latest
  prerelease: true
  file:
    - "COMOKIT-Win.zip"
    - "COMOKIT-Mac.zip"
    - "COMOKIT-Linux.zip"
  skip_cleanup: true
  on:
    repo: COMOKIT/COMOKIT-Model
    branch: master
    tags: false
  api_key: $GITHUB_API_KEY