dist: bionic
branches:
  only:
  - master
before_script:
- GAMA_LINUX=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_withJDK_Linux | cut -d ':' -f 2,3 | tr -d \")
- GAMA_MAC=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_withJDK_Mac | cut -d ':' -f 2,3 | tr -d \")
- GAMA_WINDOWS=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_withJDK_Win | cut -d ':' -f 2,3 | tr -d \")
script:
# Linux build
- curl -o gama.zip -fSL $GAMA_LINUX
- unzip gama.zip -d ./GAMA
- chmod +x ./GAMA/headless/gama-headless.sh
# Create Library folders
- mkdir -p ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
- cp -r COMOKIT ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
- zip -r ./COMOKIT-Linux.zip ./GAMA

# Clean GAMA version
- rm -fr ./GAMA

# Mac build
- curl -o gama.zip -fSL $GAMA_MAC
- unzip gama.zip -d ./GAMA
- chmod +x ./GAMA/Gama.app/Contents/headless/gama-headless.sh
# Create Library folders
- mkdir -p ./GAMA/Gama.app/Contents/Eclipse/configuration/org.eclipse.osgi/15/0/.cp/models/
- cp -r COMOKIT ./GAMA/Gama.app/Contents/Eclipse/configuration/org.eclipse.osgi/15/0/.cp/models/
- zip -r ./COMOKIT-Mac.zip ./GAMA/Gama.app

# Clean GAMA version
- rm -fr ./GAMA

# Windows build
- curl -o gama.zip -fSL $GAMA_WINDOWS
- unzip gama.zip -d ./GAMA
# Create Library folders
- mkdir -p ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
- cp -r COMOKIT ./GAMA/configuration/org.eclipse.osgi/15/0/.cp/models/
- zip -r ./COMOKIT-Win.zip ./GAMA

deploy:
  provider: releases
  name: "All-In-One Archive"
  body: "Prerelease of COMOKIT archived with GAMA JDK Continuous and COMOKIT's default models (in Library model)"
  overwrite: true
  tag_name: latest
  prerelease: true
  file:
    - "COMOKIT-Win.zip"
    - "COMOKIT-Mac.zip"
    - "COMOKIT-Linux.zip"
  skip_cleanup: true
  on:
    repo: COMOKIT/COMOKIT-Model
    branch: master
    tags: false
  api_key:
    secure: Whzxvz+GZpaBqYVAQ6fAiUrMoQu39U0E6jZ8UdaYxX2oyC7NoJwR/fQ/DzIaOyo6TNYEZSDFDt8DrNwa+h2Uetin2WxwYnRQMBQalWBfdeieoxlqc2o5u+MIHKZ8+uvL2USH52crs7boZ4NOkzvCCNKX5oelCOCYtELhySjr0J+5dAgxQAib6+W+fZTb40X5meonirUZUm7fjq5EW3YFkUupKOxUuS1UhgUJL1eRNBokIfnZQRP0ARMUTsg6qLstv5Ts+LCWAzoZwO3ZlzyxK5lcsF//nM0AwvtbFV4p0s3yC4nyB0QJYbKbMs+x58F7I8iH6dTOxMvyMA/UKDa/df9P/3AJXjgK3/CdcS2/K1nHygMBZR+eLA0ggCo4t3tHE5KkSYxnfAdK7BEMa+LPCYtL+2fiNpIYcIRF/WkIUPf00i2ckg85ep6Ucf3o4EdreJWBxmY5B9tzNCtm+/lTO0zuCglZ7/tq1EkKLeReRdcMPsQojfZekF4lPq8IrbX/Ntz/mx+7vkcs4FfTfS6zpCPv72Q/Q7FBrA0LAYISQTBL8tq4cWJE4MfKHjHL1j/Xxa6VAybZFPFMXBLssWzhK6eLnoyaIOCOqsEI6EZhraFw9duazhn31QrB74tHSp7ufsrY+hjNFdKa0GQ2LmfGe8OjvjWww0P2DHkVna6oOvI=