# This is a basic workflow to help you get started with Actions
name: Release CI master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on:
#  push:
#    branches: master
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 0 * * *' #every day

defaults:
  run:
    shell: bash
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Move COMOKIT under single folder
      run: mkdir COMOKIT && find . -maxdepth 1 -not -name ".*" | grep -v COMOKIT| xargs -i mv {} ./COMOKIT

    - name: Download latest GAMA Continuous version
      uses: wei/curl@master
      with:
        args: -o gama.zip -fSL $(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_Linux | cut -d ":" -f 2,3 | tr -d \")
    
    - name: Prepare GAMA
      run: unzip gama.zip -d $GITHUB_WORKSPACE/GAMA && rm gama.zip && chmod +x GAMA/headless/gama-headless.sh

    - name: Get COMOKIT ToolKit scripts/
      run: git clone https://github.com/COMOKIT/COMO-TK.git
      
    - name: Prepare release
      run: zip COMOKIT.zip COMOKIT GAMA COMO-TK
        
    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        # File to upload to the release
        file: COMOKIT.zip
        # Path to changelog file
        #changelogs: # optional
